"""Versioned Linux Firefox Persona templates and deterministic generation.

This module deliberately contains no browser probing.  A probe supplies a
``CapabilitySnapshot`` and a set of ``CapabilityEvidence`` records; the
generator only admits a combination to the default pool when those records
cover the exact expanded configuration and the same environment fingerprint.
"""

from __future__ import annotations

import copy
import hashlib
import json
import math
import random
import re
import secrets
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, MutableMapping, Sequence
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


TEMPLATE_SCHEMA_VERSION = 1
PERSONA_SCHEMA_VERSION = 1
SNAPSHOT_SCHEMA_VERSION = 1
GENERATOR_VERSION = "1.0.0"
SUPPORTED_GENERATOR_MAJOR = 1
VALID_TEMPLATE_STATUSES = frozenset({"candidate", "validated", "disabled"})
VALID_CAPABILITY_STATUSES = frozenset({"supported", "partial", "unsupported", "unknown"})


class PersonaError(ValueError):
    """Base class for malformed or unusable Persona data."""


class SchemaVersionError(PersonaError):
    """Raised when persisted data uses a schema this code cannot read."""


class IncompatibleVersionError(SchemaVersionError):
    """Raised when a Persona was generated by an incompatible generator."""


class TemplateError(PersonaError):
    """Raised when a template violates the template schema or constraints."""


class QualificationError(PersonaError):
    """Raised when qualification evidence is incomplete or mismatched."""


class NoEligiblePersonaError(QualificationError):
    """Raised when no strict or experimental template can be selected."""


def _canonical(value: Any) -> str:
    """Encode JSON deterministically for IDs and evidence fingerprints."""
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _digest(value: Any) -> str:
    return hashlib.sha256(_canonical(value).encode("utf-8")).hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _require_mapping(value: Any, name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise PersonaError(f"{name} must be an object")
    return value


def _deep_merge(base: Mapping[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    """Merge nested template objects without mutating either input."""
    result: dict[str, Any] = copy.deepcopy(dict(base))
    for key, value in overlay.items():
        if isinstance(value, Mapping) and isinstance(result.get(key), Mapping):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def _validate_expanded_config(config: Mapping[str, Any], template_id: str) -> None:
    """Validate finite, bounded settings and their cross-field relationships."""
    def fail(message: str) -> None:
        raise TemplateError(f"template {template_id}: {message}")

    def integer(value: Any, maximum: int) -> bool:
        return type(value) is int and 0 < value <= maximum

    browser = config.get("browser")
    cpu = config.get("cpu")
    display = config.get("display")
    locale = config.get("locale")
    if not isinstance(browser, Mapping) or browser.get("family") != "firefox":
        fail("browser.family must be firefox")
    if any(not isinstance(browser.get(key), str) or not browser[key]
           for key in ("platform", "oscpu", "firefox_version", "user_agent")):
        fail("browser identity fields must be non-empty strings")
    if not isinstance(cpu, Mapping) or not integer(cpu.get("hardware_concurrency"), 64):
        fail("cpu.hardware_concurrency must be an integer from 1 to 64")
    if not isinstance(display, Mapping):
        fail("display is required")
    for name, maximum in (("screen_width", 7680), ("screen_height", 4320)):
        if not integer(display.get(name), maximum):
            fail(f"display.{name} must be an integer from 1 to {maximum}")
    dpr = display.get("device_pixel_ratio")
    if type(dpr) not in (int, float) or not math.isfinite(dpr) or dpr <= 0:
        fail("display.device_pixel_ratio must be finite and positive")
    for name, screen in (("window_width", "screen_width"), ("window_height", "screen_height"),
                         ("avail_width", "screen_width"), ("avail_height", "screen_height")):
        if name in display and not integer(display[name], display[screen]):
            fail(f"display.{name} must be positive and within the screen")
    if not isinstance(locale, Mapping) or not isinstance(locale.get("locale"), str) or not locale["locale"]:
        fail("locale is required")
    try:
        ZoneInfo(locale.get("timezone"))
    except (ZoneInfoNotFoundError, ValueError, TypeError):
        fail("timezone must name a valid IANA timezone")
    languages = locale.get("languages")
    if (not isinstance(languages, (list, tuple)) or not languages
            or any(not isinstance(item, str) or not item.strip() for item in languages)
            or languages[0] != locale["locale"]):
        fail("languages must begin with locale")
    header = locale.get("accept_language")
    if not isinstance(header, str):
        fail("accept_language is required")
    parts = header.split(",")
    header_languages = []
    for part in parts:
        match = re.fullmatch(r"\s*([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)(?:\s*;\s*q=(0(?:\.\d{1,3})?|1(?:\.0{1,3})?))?\s*", part)
        if not match:
            fail("accept_language is malformed")
        header_languages.append(match.group(1).lower())
    if header_languages != [item.lower() for item in languages]:
        fail("accept_language sequence must match languages")

    fonts = config.get("fonts")
    if template_id in {"linux-firefox-fonts-glx-v1", "linux-firefox-workers-glx-v1", "linux-firefox-audio-glx-v1", "linux-firefox-media-glx-v1"} and fonts is None:
        fail("font preset requires fonts")
    if fonts is not None:
        if not isinstance(fonts, Mapping) or fonts.get("policy") != "whitelist":
            fail("fonts must declare a whitelist policy")
        families = fonts.get("families")
        def font_names(value):
            return isinstance(value, (list, tuple)) and all(
                isinstance(name, str) and name.strip() and len(name) <= 128
                and not any(char in name for char in (",", "\n", "\r", "\x00")) for name in value)
        if not font_names(families) or not 1 <= len(families) <= 16 or len(set(families)) != len(families):
            fail("fonts.families must contain unique bounded family names")
        blocked = fonts.get("blocked_families")
        if not font_names(blocked) or not blocked or set(families) & set(blocked):
            fail("fonts.blocked_families must be nonempty and disjoint")
        local_names = fonts.get("local_names", {})
        if (not isinstance(local_names, Mapping)
                or not set(local_names).issubset(set(families) | set(blocked))
                or not font_names(list(local_names.values()))):
            fail("font local names must name selected or blocked font faces")
        aliases = fonts.get("aliases")
        if (not isinstance(aliases, Mapping)
                or not {"sans-serif", "serif", "monospace"}.issubset(aliases)
                or not set(aliases).issubset({"sans-serif", "serif", "monospace", "emoji", "cjk"})
                or any(value not in families for value in aliases.values())):
            fail("font aliases must refer to selected families")
        samples = fonts.get("samples")
        if (not isinstance(samples, Mapping) or set(samples) != set(families)
                or any(not isinstance(value, str) or not value.strip() or len(value) > 256 for value in samples.values())):
            fail("every selected font requires a bounded rendering sample")
    appearance = config.get("appearance")
    if appearance is not None:
        if not isinstance(appearance, Mapping):
            fail("appearance must be an object")
        if appearance.get("color_scheme") not in ("light", "dark"):
            fail("appearance.color_scheme must be light or dark")
        if appearance.get("contrast", "no-preference") not in ("no-preference", "more", "less", "custom"):
            fail("appearance.contrast is invalid")
        for name in ("reduced_motion", "forced_colors"):
            if type(appearance.get(name)) is not bool:
                fail(f"appearance.{name} must be a boolean")
    geolocation = config.get("geolocation")
    if geolocation is not None:
        if not isinstance(geolocation, Mapping):
            fail("geolocation must be an object")
        for name, minimum, maximum in (("latitude", -90, 90), ("longitude", -180, 180),
                                       ("accuracy", 0, 100000)):
            value = geolocation.get(name)
            if type(value) not in (int, float) or not math.isfinite(value) or not minimum <= value <= maximum:
                fail(f"geolocation.{name} must be finite and within {minimum}..{maximum}")
        if geolocation.get("permission") not in ("prompt", "granted", "denied"):
            fail("geolocation.permission is invalid")
    # Region relationships belong to this finite preset family, not to every
    # multilingual desktop. Other families can define different relationships.
    if template_id in {"linux-firefox-region-appearance-v1", "linux-firefox-software-glx-v1", "linux-firefox-fonts-glx-v1", "linux-firefox-workers-glx-v1", "linux-firefox-audio-glx-v1", "linux-firefox-media-glx-v1"}:
        regions = {"zh-CN": ("Asia/Shanghai", 31.2304, 121.4737),
                   "en-US": ("America/New_York", 40.7128, -74.0060)}
        expected = regions.get(locale["locale"])
        if (expected is None or geolocation is None or appearance is None
                or (locale["timezone"], geolocation["latitude"], geolocation["longitude"]) != expected):
            fail("geolocation and timezone must match this preset's locale region")
        if "contrast" not in appearance:
            fail("regional appearance requires an explicit contrast preference")
    if template_id in {"linux-firefox-software-glx-v1", "linux-firefox-fonts-glx-v1", "linux-firefox-workers-glx-v1", "linux-firefox-audio-glx-v1", "linux-firefox-media-glx-v1"}:
        graphics = config.get("graphics")
        expected_graphics = {
            "identity_class": "native-linux-firefox", "hardware_class": "software",
            "execution_backend": "software", "context_backend": "glx", "vendor": "Mesa",
            "renderer": "llvmpipe, or similar", "webgl1": True, "webgl2": True,
        }
        if (not isinstance(graphics, Mapping)
                or any(graphics.get(name) != value or type(graphics.get(name)) is not type(value)
                       for name, value in expected_graphics.items())):
            fail("software GLX graphics must match the measured Mesa software identity")
    worker_graphics = config.get("worker_graphics")
    if template_id in {"linux-firefox-workers-glx-v1", "linux-firefox-audio-glx-v1", "linux-firefox-media-glx-v1"} and worker_graphics is None:
        fail("Worker graphics preset requires worker_graphics")
    if worker_graphics is not None:
        if (not isinstance(worker_graphics, Mapping)
                or set(worker_graphics) != {"contexts", "fonts", "webgl"}
                or worker_graphics.get("contexts") != ["dedicated", "shared", "service"]
                or worker_graphics.get("fonts") is not True
                or worker_graphics.get("webgl") is not True):
            fail("worker_graphics must require fonts and WebGL in dedicated, shared and service contexts")
    audio = config.get("audio")
    if template_id in {"linux-firefox-audio-glx-v1", "linux-firefox-media-glx-v1"} and audio is None:
        fail("audio preset requires audio")
    if audio is not None:
        if not isinstance(appearance, Mapping) or appearance.get("color_scheme") not in {"light", "dark"}:
            fail("audio preset requires a valid appearance color scheme")
        # These are finite preset choices, not a general relationship between
        # visual appearance and audio hardware capabilities.
        expected_audio = {
            "sample_rate": 44100 if appearance["color_scheme"] == "light" else 48000,
            "channels": 2, "frames": 2048, "rendering": "native",
            "physical_output": "not_verified", "physical_input": "not_verified",
        }
        if (not isinstance(audio, Mapping) or set(audio) != set(expected_audio)
                or any(type(audio.get(name)) is not type(value) or audio.get(name) != value
                       for name, value in expected_audio.items())):
            fail("audio must match the finite native preset and leave physical input/output unverified")


    media = config.get("media")
    if template_id == "linux-firefox-media-glx-v1" and media is None:
        fail("media preset requires media")
    if media is not None:
        expected_media = {
            "fixture_set": "native-codecs-v1",
            "codecs": ["h264", "vp8", "vp9", "av1", "aac", "opus"],
            "scope": "native-decode-playback", "physical_input": "not_verified",
            "physical_output": "not_verified", "webrtc": "not_verified",
        }
        if (not isinstance(media, Mapping) or set(media) != set(expected_media)
                or any(type(media.get(name)) is not type(value) or media.get(name) != value
                       for name, value in expected_media.items())):
            fail("media must match the finite native fixture preset without physical device or WebRTC claims")


def _matches_template(template: "PersonaTemplate", config: Mapping[str, Any],
                      runtime_version: str | None = None) -> bool:
    if template.status == "disabled":
        return False
    try:
        _validate_expanded_config(config, template.template_id)
        version = runtime_version or config["browser"]["firefox_version"]
        # Unexpanded experimental templates may retain the runtime placeholder.
        expected = template.expand(config.get("variant_index"), None if version == "runtime" else version)
        return _canonical(expected) == _canonical(config)
    except (PersonaError, TypeError, KeyError, ValueError):
        return False


def _evidence_reasons(template: "PersonaTemplate", evidence: Iterable["CapabilityEvidence"],
                      fingerprint: str) -> list[str]:
    reasons = []
    by_capability: dict[str, list[CapabilityEvidence]] = {}
    for item in evidence:
        by_capability.setdefault(item.capability, []).append(item)
    if not template.required_capabilities:
        reasons.append("template has no required capabilities")
    for capability in template.required_capabilities:
        records = by_capability.get(capability, [])
        if not records:
            reasons.append(f"missing evidence: {capability}")
            continue
        if len({_canonical({"requested": item.requested, "observed": item.observed})
                for item in records}) > 1:
            reasons.append(f"conflicting evidence: {capability}")
        for item in records:
            if item.environment_fingerprint != fingerprint:
                reasons.append(f"evidence environment mismatch: {capability}")
            if item.status != "supported":
                reasons.append(f"capability is not supported: {capability}")
            for name in ("proof", "contexts"):
                values = getattr(item, name)
                if (not isinstance(values, (tuple, list)) or not values
                        or any(not isinstance(value, str) or not value.strip() for value in values)):
                    reasons.append(f"evidence {name} is empty or invalid: {capability}")
            # False and zero are meaningful measurements; empty containers are not.
            for name in ("requested", "observed"):
                value = getattr(item, name)
                if (value is None or (isinstance(value, str) and not value.strip())
                        or (isinstance(value, (list, tuple, dict)) and not value)):
                    reasons.append(f"evidence {name} is empty: {capability}")
    return list(dict.fromkeys(reasons))


def _version_major(value: str) -> int:
    try:
        return int(str(value).split(".", 1)[0])
    except (TypeError, ValueError):
        raise IncompatibleVersionError(f"invalid generator version: {value!r}")


def combination_fingerprint(template_id: str, template_version: str, final_config: Mapping[str, Any]) -> str:
    """Return the digest for one fully expanded template combination."""
    return _digest({
        "template_id": template_id,
        "template_version": template_version,
        "final_config": final_config,
    })


@dataclass(frozen=True)
class CapabilitySnapshot:
    """A versioned, environment-bound snapshot supplied by the browser probe.

    ``environment`` must identify the Firefox/Termux/backend build.  The
    fingerprint is calculated from environment and capabilities, excluding
    collection timestamps, so two equivalent probes bind to the same evidence
    namespace.  A caller may pass a mapping to :meth:`from_mapping` when
    reading probe JSON.
    """

    environment: Mapping[str, Any]
    capabilities: Mapping[str, Any]
    schema_version: int = SNAPSHOT_SCHEMA_VERSION
    source_id: str | None = None
    fingerprint: str = field(init=False)

    def __post_init__(self) -> None:
        if type(self.schema_version) is not int or self.schema_version != SNAPSHOT_SCHEMA_VERSION:
            raise SchemaVersionError(
                f"unsupported capability snapshot schema {self.schema_version!r}"
            )
        _require_mapping(self.environment, "snapshot.environment")
        _require_mapping(self.capabilities, "snapshot.capabilities")
        payload = {
            "schema_version": self.schema_version,
            "environment": dict(self.environment),
            "capabilities": dict(self.capabilities),
        }
        computed = _digest(payload)
        if self.source_id is not None and not isinstance(self.source_id, str):
            raise QualificationError("snapshot source_id must be a string")
        # Probe adapters may publish an environment digest as ``id``.  Keep
        # that digest as the binding identity, while nested persisted snapshots
        # without a source id use our canonical digest.
        object.__setattr__(self, "fingerprint", self.source_id or computed)

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | "CapabilitySnapshot") -> "CapabilitySnapshot":
        if isinstance(value, cls):
            return value
        data = _require_mapping(value, "capability_snapshot")
        version = data.get("schema_version", SNAPSHOT_SCHEMA_VERSION)
        is_flat_probe = "environment" not in data and "capabilities" not in data
        if is_flat_probe:
            # The manager's probe contract is intentionally simple: a flat
            # environment mapping with an ``id`` digest.  Capabilities may be
            # nested when available, but are not required for phase zero.
            environment = dict(data)
            source_id = environment.pop("id", None)
            capabilities = {}
        else:
            environment = _require_mapping(data.get("environment", {}), "snapshot.environment")
            capabilities = _require_mapping(data.get("capabilities", {}), "snapshot.capabilities")
            source_id = data.get("id")
        snapshot = cls(
            environment=copy.deepcopy(environment),
            capabilities=copy.deepcopy(capabilities),
            schema_version=version,
            source_id=str(source_id) if source_id is not None else None,
        )
        expected = data.get("fingerprint")
        if expected is not None and expected != snapshot.fingerprint:
            raise QualificationError("capability snapshot fingerprint does not match its contents")
        return snapshot

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "environment": copy.deepcopy(dict(self.environment)),
            "capabilities": copy.deepcopy(dict(self.capabilities)),
            "id": self.source_id,
            "fingerprint": self.fingerprint,
        }

    @property
    def id(self) -> str:
        """Probe-facing alias for the immutable environment fingerprint."""
        return self.fingerprint


@dataclass(frozen=True)
class CapabilityEvidence:
    """One probe result, explicitly tied to a capability snapshot."""

    capability: str
    status: str
    environment_fingerprint: str
    observed: Any = None
    requested: Any = None
    contexts: tuple[str, ...] = ()
    proof: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.capability or not isinstance(self.capability, str):
            raise QualificationError("evidence capability must be a non-empty string")
        if self.status not in VALID_CAPABILITY_STATUSES:
            raise QualificationError(f"unknown capability evidence status: {self.status!r}")
        if not isinstance(self.environment_fingerprint, str) or not self.environment_fingerprint:
            raise QualificationError("capability evidence must name an environment fingerprint")

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | "CapabilityEvidence") -> "CapabilityEvidence":
        if isinstance(value, cls):
            return value
        data = _require_mapping(value, "evidence")
        contexts = data.get("contexts", ())
        proof = data.get("proof", ())
        if isinstance(contexts, str) or not isinstance(contexts, Sequence):
            raise QualificationError("evidence.contexts must be an array")
        if isinstance(proof, str) or not isinstance(proof, Sequence):
            raise QualificationError("evidence.proof must be an array")
        return cls(
            capability=str(data.get("capability", "")),
            status=str(data.get("status", "unknown")),
            environment_fingerprint=str(data.get("environment_fingerprint", "")),
            observed=copy.deepcopy(data.get("observed")),
            requested=copy.deepcopy(data.get("requested")),
            contexts=tuple(contexts),
            proof=tuple(proof),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "capability": self.capability,
            "status": self.status,
            "environment_fingerprint": self.environment_fingerprint,
            "observed": copy.deepcopy(self.observed),
            "requested": copy.deepcopy(self.requested),
            "contexts": list(self.contexts),
            "proof": list(self.proof),
        }


@dataclass(frozen=True)
class PersonaTemplate:
    """Immutable validated representation of one template JSON object."""

    template_id: str
    version: str
    status: str
    strict_eligible: bool
    base_config: Mapping[str, Any]
    variants: tuple[Mapping[str, Any], ...]
    required_capabilities: tuple[str, ...]
    metadata: Mapping[str, Any] = field(default_factory=dict)
    schema_version: int = TEMPLATE_SCHEMA_VERSION

    def __post_init__(self) -> None:
        if not self.template_id or not isinstance(self.template_id, str):
            raise TemplateError("template id must be a non-empty string")
        if not self.version or not isinstance(self.version, str):
            raise TemplateError(f"template {self.template_id}: version is required")
        if self.status not in VALID_TEMPLATE_STATUSES:
            raise TemplateError(f"template {self.template_id}: invalid status {self.status!r}")
        if type(self.schema_version) is not int or self.schema_version != TEMPLATE_SCHEMA_VERSION:
            raise SchemaVersionError(
                f"template {self.template_id}: unsupported schema {self.schema_version!r}"
            )
        _require_mapping(self.base_config, f"template {self.template_id}.base_config")
        if not self.variants:
            raise TemplateError(f"template {self.template_id}: at least one variant is required")
        for index, variant in enumerate(self.variants):
            _require_mapping(variant, f"template {self.template_id}.variants[{index}]")
            config = _deep_merge(self.base_config, variant)
            _validate_expanded_config(config, self.template_id)
        if len(set(self.required_capabilities)) != len(self.required_capabilities):
            raise TemplateError(f"template {self.template_id}: duplicate required capability")

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "PersonaTemplate":
        data = _require_mapping(value, "template")
        schema = data.get("schema_version", TEMPLATE_SCHEMA_VERSION)
        required = data.get("required_capabilities", ())
        variants = data.get("variants", ())
        if isinstance(required, str) or not isinstance(required, Sequence):
            raise TemplateError("template.required_capabilities must be an array")
        if isinstance(variants, (str, bytes)) or not isinstance(variants, Sequence):
            raise TemplateError("template.variants must be an array")
        return cls(
            template_id=str(data.get("id", data.get("template_id", ""))),
            version=str(data.get("version", "")),
            status=str(data.get("status", "candidate")),
            strict_eligible=bool(data.get("strict_eligible", False)),
            base_config=copy.deepcopy(_require_mapping(data.get("base_config", {}), "template.base_config")),
            variants=tuple(copy.deepcopy(_require_mapping(item, "template.variant")) for item in variants),
            required_capabilities=tuple(str(item) for item in required),
            metadata=copy.deepcopy(_require_mapping(data.get("metadata", {}), "template.metadata")),
            schema_version=schema,
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "id": self.template_id,
            "version": self.version,
            "status": self.status,
            "strict_eligible": self.strict_eligible,
            "base_config": copy.deepcopy(dict(self.base_config)),
            "variants": copy.deepcopy([dict(item) for item in self.variants]),
            "required_capabilities": list(self.required_capabilities),
            "metadata": copy.deepcopy(dict(self.metadata)),
        }

    def expand(self, variant_index: int, runtime_browser_version: str | None = None) -> dict[str, Any]:
        if type(variant_index) is not int or not 0 <= variant_index < len(self.variants):
            raise TemplateError(f"template {self.template_id}: variant index out of range")
        config = _deep_merge(self.base_config, self.variants[variant_index])
        if runtime_browser_version:
            browser = config.setdefault("browser", {})
            if not isinstance(browser, MutableMapping):
                raise TemplateError(f"template {self.template_id}: browser config must be an object")
            browser["firefox_version"] = str(runtime_browser_version)
            major_version = str(runtime_browser_version).split(".", 1)[0]
            for key, value in list(browser.items()):
                if isinstance(value, str):
                    browser[key] = value.replace("{firefox_version_major}", major_version)
                    browser[key] = browser[key].replace("{firefox_version}", str(runtime_browser_version))
        config["template_id"] = self.template_id
        config["template_version"] = self.version
        config["variant_index"] = variant_index
        _validate_expanded_config(config, self.template_id)
        return config


@dataclass(frozen=True)
class QualificationReport:
    """Evidence report for one exact expanded combination.

    A report without ``final_config`` or with ``full_combination=False`` can
    be retained for diagnostics but can never unlock the strict pool.
    """

    template_id: str
    template_version: str
    environment_fingerprint: str
    final_config: Mapping[str, Any]
    evidence: tuple[CapabilityEvidence, ...]
    passed: bool
    full_combination: bool = True
    reasons: tuple[str, ...] = ()
    qualified_at: str = field(default_factory=_utc_now)
    schema_version: int = PERSONA_SCHEMA_VERSION
    generator_version: str = GENERATOR_VERSION
    combination_fingerprint: str = field(init=False)

    def __post_init__(self) -> None:
        if type(self.schema_version) is not int or self.schema_version != PERSONA_SCHEMA_VERSION:
            raise SchemaVersionError(f"unsupported qualification schema {self.schema_version!r}")
        if _version_major(self.generator_version) != SUPPORTED_GENERATOR_MAJOR:
            raise IncompatibleVersionError(
                f"qualification generated by incompatible generator {self.generator_version!r}"
            )
        if not self.environment_fingerprint:
            raise QualificationError("qualification report must be environment-bound")
        if not isinstance(self.final_config, Mapping) or not self.final_config:
            raise QualificationError("qualification report must include the full expanded configuration")
        object.__setattr__(
            self,
            "combination_fingerprint",
            combination_fingerprint(self.template_id, self.template_version, self.final_config),
        )

    @classmethod
    def build(
        cls,
        template: PersonaTemplate,
        final_config: Mapping[str, Any],
        snapshot: CapabilitySnapshot | Mapping[str, Any],
        evidence: Iterable[CapabilityEvidence | Mapping[str, Any]],
        *,
        full_combination: bool = True,
        generator_version: str = GENERATOR_VERSION,
    ) -> "QualificationReport":
        snapshot_obj = CapabilitySnapshot.from_mapping(snapshot)
        evidence_obj = tuple(CapabilityEvidence.from_mapping(item) for item in evidence)
        reasons = _evidence_reasons(template, evidence_obj, snapshot_obj.fingerprint)
        if not full_combination:
            reasons.append("report does not cover a complete expanded combination")
        if not _matches_template(template, final_config, snapshot_obj.environment.get("firefox_version")):
            reasons.append("expanded configuration does not match an enabled template variant")
        passed = not reasons
        return cls(
            template_id=template.template_id,
            template_version=template.version,
            environment_fingerprint=snapshot_obj.fingerprint,
            final_config=copy.deepcopy(dict(final_config)),
            evidence=evidence_obj,
            passed=passed,
            full_combination=full_combination,
            reasons=tuple(reasons),
            generator_version=generator_version,
        )

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "QualificationReport":
        data = _require_mapping(value, "qualification_report")
        schema = data.get("schema_version", PERSONA_SCHEMA_VERSION)
        evidence = data.get("evidence", ())
        if isinstance(evidence, (str, bytes)) or not isinstance(evidence, Sequence):
            raise QualificationError("qualification_report.evidence must be an array")
        report = cls(
            template_id=str(data.get("template_id", "")),
            template_version=str(data.get("template_version", "")),
            environment_fingerprint=str(data.get("environment_fingerprint", "")),
            final_config=copy.deepcopy(_require_mapping(data.get("final_config", {}), "qualification_report.final_config")),
            evidence=tuple(CapabilityEvidence.from_mapping(item) for item in evidence),
            passed=data.get("passed") is True,
            full_combination=data.get("full_combination") is True,
            reasons=tuple(str(item) for item in data.get("reasons", ())),
            qualified_at=str(data.get("qualified_at", _utc_now())),
            schema_version=schema,
            generator_version=str(data.get("generator_version", "")),
        )
        expected = data.get("combination_fingerprint")
        if expected is not None and expected != report.combination_fingerprint:
            raise QualificationError("qualification combination fingerprint does not match its contents")
        return report

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "generator_version": self.generator_version,
            "template_id": self.template_id,
            "template_version": self.template_version,
            "environment_fingerprint": self.environment_fingerprint,
            "combination_fingerprint": self.combination_fingerprint,
            "final_config": copy.deepcopy(dict(self.final_config)),
            "evidence": [item.to_dict() for item in self.evidence],
            "passed": self.passed,
            "full_combination": self.full_combination,
            "reasons": list(self.reasons),
            "qualified_at": self.qualified_at,
        }

    def usable_for(
        self,
        template: PersonaTemplate,
        final_config: Mapping[str, Any],
        snapshot: CapabilitySnapshot | Mapping[str, Any],
    ) -> bool:
        snapshot_obj = CapabilitySnapshot.from_mapping(snapshot)
        if self.passed is not True or self.full_combination is not True:
            return False
        if self.template_id != template.template_id or self.template_version != template.version:
            return False
        if self.environment_fingerprint != snapshot_obj.fingerprint:
            return False
        if self.combination_fingerprint != combination_fingerprint(
            template.template_id, template.version, final_config
        ):
            return False
        if final_config.get("template_id") != template.template_id or final_config.get("template_version") != template.version:
            return False
        return (_matches_template(template, final_config, snapshot_obj.environment.get("firefox_version"))
                and not _evidence_reasons(template, self.evidence, snapshot_obj.fingerprint))


@dataclass(frozen=True)
class Persona:
    """Persistable final Persona identity and expanded configuration."""

    persona_id: str
    seed: int
    template_id: str
    template_version: str
    final_config: Mapping[str, Any]
    capability_snapshot_fingerprint: str | None
    experimental: bool
    schema_version: int = PERSONA_SCHEMA_VERSION
    generator_version: str = GENERATOR_VERSION
    qualification: QualificationReport | None = None
    created_at: str = field(default_factory=_utc_now)

    @property
    def config(self) -> Mapping[str, Any]:
        """Compatibility alias used by the manager when applying settings."""
        return self.final_config

    @classmethod
    def build(
        cls,
        *,
        seed: int,
        template: PersonaTemplate,
        final_config: Mapping[str, Any],
        snapshot: CapabilitySnapshot | Mapping[str, Any] | None,
        experimental: bool,
        qualification: QualificationReport | None = None,
        generator_version: str = GENERATOR_VERSION,
        persona_id: str | None = None,
    ) -> "Persona":
        if not isinstance(seed, int) or isinstance(seed, bool):
            raise PersonaError("Persona seed must be an integer")
        snapshot_obj = CapabilitySnapshot.from_mapping(snapshot) if snapshot is not None else None
        config = copy.deepcopy(dict(final_config))
        # The ID intentionally excludes the current environment fingerprint:
        # an environment upgrade must reject/reauthorize a Persona rather than
        # silently changing its persistent identity.
        if persona_id is None:
            # Direct callers get a deterministic identity.  The generator
            # supplies a fresh nonce so two independently created windows can
            # legitimately share seed and final features without sharing a
            # persistence key.
            identity_payload = {
                "schema_version": PERSONA_SCHEMA_VERSION,
                "generator_version": generator_version,
                "seed": seed,
                "template_id": template.template_id,
                "template_version": template.version,
                "final_config": config,
            }
            persona_id = "persona_" + _digest(identity_payload)[:32]
        if not isinstance(persona_id, str) or len(persona_id) != 40 or not persona_id.startswith("persona_"):
            raise PersonaError("persona_id must be persona_ followed by 32 hexadecimal characters")
        try:
            int(persona_id[8:], 16)
        except ValueError as exc:
            raise PersonaError("persona_id must be persona_ followed by 32 hexadecimal characters") from exc
        if qualification is not None:
            if snapshot_obj is None or not qualification.usable_for(template, config, snapshot_obj):
                raise QualificationError("qualification does not match the Persona combination")
        return cls(
            persona_id=persona_id,
            seed=seed,
            template_id=template.template_id,
            template_version=template.version,
            final_config=config,
            capability_snapshot_fingerprint=snapshot_obj.fingerprint if snapshot_obj else None,
            experimental=experimental,
            schema_version=PERSONA_SCHEMA_VERSION,
            generator_version=generator_version,
            qualification=qualification,
        )

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "Persona":
        data = _require_mapping(value, "persona")
        schema = data.get("schema_version")
        if type(schema) is not int or schema != PERSONA_SCHEMA_VERSION:
            raise SchemaVersionError(f"unsupported Persona schema {schema!r}")
        generator_version = str(data.get("generator_version", ""))
        if _version_major(generator_version) != SUPPORTED_GENERATOR_MAJOR:
            raise IncompatibleVersionError(
                f"Persona generated by incompatible generator {generator_version!r}"
            )
        final_config = copy.deepcopy(_require_mapping(data.get("final_config", {}), "persona.final_config"))
        if not data.get("persona_id") or type(data.get("seed")) is not int:
            raise PersonaError("persona_id and integer seed are required")
        _validate_expanded_config(final_config, str(data.get("template_id", "")))
        if (not data.get("template_id") or not data.get("template_version")
                or final_config.get("template_id") != data["template_id"]
                or final_config.get("template_version") != data["template_version"]
                or type(final_config.get("variant_index")) is not int
                or final_config["variant_index"] < 0):
            raise PersonaError("persisted configuration template identity is invalid")
        if type(data.get("experimental")) is not bool:
            raise PersonaError("experimental must be a boolean")
        qualification_data = data.get("qualification")
        qualification = (
            QualificationReport.from_mapping(qualification_data)
            if qualification_data is not None
            else None
        )
        if qualification is not None and (
                qualification.template_id != data["template_id"]
                or qualification.template_version != data["template_version"]
                or qualification.environment_fingerprint != data.get("capability_snapshot_fingerprint")
                or qualification.combination_fingerprint != combination_fingerprint(
                    data["template_id"], data["template_version"], final_config)):
            raise QualificationError("persisted qualification does not match the Persona combination")
        if data["experimental"] is False and (
                qualification is None or qualification.passed is not True
                or qualification.full_combination is not True):
            raise QualificationError("strict Persona requires a passed full-combination qualification")
        persona = cls(
            persona_id=str(data["persona_id"]),
            seed=int(data["seed"]),
            template_id=str(data.get("template_id", "")),
            template_version=str(data.get("template_version", "")),
            final_config=final_config,
            capability_snapshot_fingerprint=(
                str(data["capability_snapshot_fingerprint"])
                if data.get("capability_snapshot_fingerprint") is not None
                else None
            ),
            experimental=bool(data.get("experimental", False)),
            schema_version=schema,
            generator_version=generator_version,
            qualification=qualification,
            created_at=str(data.get("created_at", _utc_now())),
        )
        if len(persona.persona_id) != 40 or not persona.persona_id.startswith("persona_"):
            raise PersonaError("invalid persisted persona_id")
        try:
            int(persona.persona_id[8:], 16)
        except ValueError as exc:
            raise PersonaError("invalid persisted persona_id") from exc
        return persona

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "generator_version": self.generator_version,
            "persona_id": self.persona_id,
            "seed": self.seed,
            "template_id": self.template_id,
            "template_version": self.template_version,
            "final_config": copy.deepcopy(dict(self.final_config)),
            "capability_snapshot_fingerprint": self.capability_snapshot_fingerprint,
            "experimental": self.experimental,
            "qualification": self.qualification.to_dict() if self.qualification else None,
            "created_at": self.created_at,
        }


class TemplateCatalog:
    """Load templates and retain exact-combination qualification reports."""

    def __init__(self, templates: Iterable[PersonaTemplate] = ()) -> None:
        self._templates: dict[str, PersonaTemplate] = {}
        self._reports: dict[tuple[str, str, str, str], QualificationReport] = {}
        for template in templates:
            self.add(template)

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any]) -> "TemplateCatalog":
        data = _require_mapping(value, "template catalog")
        schema = data.get("schema_version", TEMPLATE_SCHEMA_VERSION)
        if schema != TEMPLATE_SCHEMA_VERSION:
            raise SchemaVersionError(f"unsupported template catalog schema {schema!r}")
        templates = data.get("templates", ())
        if isinstance(templates, (str, bytes)) or not isinstance(templates, Sequence):
            raise TemplateError("template catalog.templates must be an array")
        return cls(PersonaTemplate.from_mapping(item) for item in templates)

    @classmethod
    def from_path(cls, path: str | Path) -> "TemplateCatalog":
        path_obj = Path(path)
        if path_obj.is_dir():
            files = sorted(path_obj.glob("*.json"))
            if not files:
                raise TemplateError(f"no template JSON files found in {path_obj}")
            catalogs = []
            for file in files:
                with file.open("r", encoding="utf-8") as handle:
                    catalogs.append(json.load(handle))
            catalog = cls()
            for value in catalogs:
                loaded = cls.from_mapping(value)
                for template in loaded.templates:
                    catalog.add(template)
            return catalog
        with path_obj.open("r", encoding="utf-8") as handle:
            return cls.from_mapping(json.load(handle))

    @classmethod
    def load(cls, path: str | Path) -> "TemplateCatalog":
        """Named alias used by manager integrations."""
        return cls.from_path(path)

    @classmethod
    def default(cls) -> "TemplateCatalog":
        return cls.from_path(Path(__file__).with_name("templates"))

    @property
    def templates(self) -> tuple[PersonaTemplate, ...]:
        return tuple(self._templates[key] for key in sorted(self._templates))

    def add(self, template: PersonaTemplate | Mapping[str, Any]) -> PersonaTemplate:
        value = PersonaTemplate.from_mapping(template) if not isinstance(template, PersonaTemplate) else template
        if value.template_id in self._templates:
            raise TemplateError(f"duplicate template id: {value.template_id}")
        self._templates[value.template_id] = value
        return value

    def get(self, template_id: str) -> PersonaTemplate:
        try:
            return self._templates[template_id]
        except KeyError:
            raise TemplateError(f"unknown template: {template_id}")

    def qualify(
        self,
        template_id: str,
        final_config: Mapping[str, Any],
        snapshot: CapabilitySnapshot | Mapping[str, Any],
        evidence: Iterable[CapabilityEvidence | Mapping[str, Any]],
        *,
        full_combination: bool = True,
    ) -> QualificationReport:
        template = self.get(template_id)
        report = QualificationReport.build(
            template,
            final_config,
            CapabilitySnapshot.from_mapping(snapshot),
            evidence,
            full_combination=full_combination,
        )
        return report

    def promote(self, report: QualificationReport | Mapping[str, Any]) -> QualificationReport:
        """Explicitly add one passed full-combination report to the strict pool.

        Promotion never turns an iGPU candidate into strict eligibility merely
        because its JSON says ``strict_eligible``.  The report must be passed
        explicitly and is indexed by its exact environment and combination.
        """
        report_obj = QualificationReport.from_mapping(report) if not isinstance(report, QualificationReport) else report
        template = self.get(report_obj.template_id)
        if report_obj.template_version != template.version:
            raise QualificationError("qualification report template version is stale")
        if report_obj.passed is not True or report_obj.full_combination is not True:
            raise QualificationError("only a passed full-combination report can be promoted")
        if (not _matches_template(template, report_obj.final_config)
                or _evidence_reasons(template, report_obj.evidence, report_obj.environment_fingerprint)):
            raise QualificationError("qualification evidence or template combination is invalid")
        key = (
            report_obj.template_id,
            report_obj.template_version,
            report_obj.environment_fingerprint,
            report_obj.combination_fingerprint,
        )
        self._reports[key] = report_obj
        return report_obj

    def report_for(
        self,
        template: PersonaTemplate,
        final_config: Mapping[str, Any],
        snapshot: CapabilitySnapshot,
    ) -> QualificationReport | None:
        return self._reports.get((
            template.template_id,
            template.version,
            snapshot.fingerprint,
            combination_fingerprint(template.template_id, template.version, final_config),
        ))

    def reports(self) -> tuple[QualificationReport, ...]:
        return tuple(self._reports[key] for key in sorted(self._reports))


class PersonaGenerator:
    """Create deterministic Personas from a catalog and probe snapshot."""

    def __init__(
        self,
        catalog: TemplateCatalog | None = None,
        capability_snapshot: CapabilitySnapshot | Mapping[str, Any] | None = None,
        *,
        reports: Iterable[QualificationReport | Mapping[str, Any]] = (),
        runtime_browser_version: str | None = None,
    ) -> None:
        self.catalog = catalog or TemplateCatalog.default()
        self.capability_snapshot = (
            CapabilitySnapshot.from_mapping(capability_snapshot)
            if capability_snapshot is not None
            else None
        )
        for report in reports:
            self.catalog.promote(report)
        self.runtime_browser_version = runtime_browser_version

    def _ordered_options(self, seed: int, experimental: bool) -> list[tuple[PersonaTemplate, int, dict[str, Any]]]:
        rng = random.Random(seed)
        templates = [template for template in self.catalog.templates if template.status != "disabled"]
        options: list[tuple[PersonaTemplate, int, dict[str, Any]]] = []
        for template in templates:
            for variant_index in range(len(template.variants)):
                options.append((template, variant_index, template.expand(variant_index, self.runtime_browser_version)))
        rng.shuffle(options)
        return options

    def create(self, seed: int | None = None, *, experimental: bool = False) -> Persona:
        if seed is None:
            seed = secrets.randbits(128)
        if not isinstance(seed, int) or isinstance(seed, bool):
            raise PersonaError("Persona seed must be an integer")
        if not experimental and self.capability_snapshot is None:
            raise QualificationError(
                "strict Persona creation requires a capability snapshot and promoted full-combination evidence"
            )
        attempted = 0
        for template, variant_index, config in self._ordered_options(seed, experimental):
            attempted += 1
            report = None
            if not experimental:
                report = self.catalog.report_for(template, config, self.capability_snapshot)  # type: ignore[arg-type]
                if report is None or not report.usable_for(template, config, self.capability_snapshot):  # type: ignore[arg-type]
                    continue
            return Persona.build(
                seed=seed,
                template=template,
                final_config=config,
                snapshot=self.capability_snapshot,
                experimental=experimental,
                qualification=report,
                generator_version=GENERATOR_VERSION,
                persona_id="persona_" + uuid.uuid4().hex,
            )
        mode = "experimental" if experimental else "strict"
        raise NoEligiblePersonaError(f"no eligible {mode} Persona combinations (checked {attempted} variants)")

    def generate(self, seed: int | None = None, *, experimental: bool = False) -> Persona:
        """Alias for :meth:`create`; useful when the caller says generate."""
        return self.create(seed, experimental=experimental)


def create(
    *,
    seed: int | None = None,
    experimental: bool = False,
    catalog: TemplateCatalog | None = None,
    capability_snapshot: CapabilitySnapshot | Mapping[str, Any] | None = None,
    reports: Iterable[QualificationReport | Mapping[str, Any]] = (),
    runtime_browser_version: str | None = None,
) -> Persona:
    """Convenience API used by the manager for one new Persona."""
    return PersonaGenerator(
        catalog,
        capability_snapshot,
        reports=reports,
        runtime_browser_version=runtime_browser_version,
    ).create(seed, experimental=experimental)


def qualify(
    template: PersonaTemplate,
    final_config: Mapping[str, Any],
    snapshot: CapabilitySnapshot | Mapping[str, Any],
    evidence: Iterable[CapabilityEvidence | Mapping[str, Any]],
    *,
    full_combination: bool = True,
) -> QualificationReport:
    """Build a qualification report without mutating the catalog."""
    return QualificationReport.build(
        template,
        final_config,
        CapabilitySnapshot.from_mapping(snapshot),
        evidence,
        full_combination=full_combination,
    )


def promote(catalog: TemplateCatalog, report: QualificationReport | Mapping[str, Any]) -> QualificationReport:
    """Explicit report promotion helper for probe/manager integration."""
    return catalog.promote(report)


__all__ = [
    "CapabilityEvidence",
    "CapabilitySnapshot",
    "GENERATOR_VERSION",
    "IncompatibleVersionError",
    "NoEligiblePersonaError",
    "PERSONA_SCHEMA_VERSION",
    "Persona",
    "PersonaError",
    "PersonaGenerator",
    "PersonaTemplate",
    "QualificationError",
    "QualificationReport",
    "SchemaVersionError",
    "SNAPSHOT_SCHEMA_VERSION",
    "TEMPLATE_SCHEMA_VERSION",
    "TemplateCatalog",
    "TemplateError",
    "combination_fingerprint",
    "create",
    "promote",
    "qualify",
]
